#!/usr/bin/env bash

#
# Check bin files for any changes/tampering.
# - Niklas Schultz
#

##############################################################################
#
# Global function definitions
#
##############################################################################

check_sha256sum_authentication ()
{
    printf "Checking sha256sum byte size... "
    size_in_bytes=$(du -b /usr/bin/sha256sum | awk '{print $1}')
    if [ "$size_in_bytes" != "59768" ]; then
        printf "suspicous\n"
        exit 1
    else
        printf "ok\n"
    fi

    printf "Checking sha256sum last modification date... "
    last_mod_time=$(date -r /usr/bin/sha256sum)
    if [ "$last_mod_time" != "Thu 05 Sep 2019 12:38:40 PM CEST" ]; then
        printf "suspicous\n"
        exit 1
    else
        printf "ok\n"
    fi

    printf "Checking sha256sum hash value 1..."
    trusted_hash_value="b693d4bd026ba1515edacabcadbd6785454b08ec9468665e4dc33f01df8cc659"
    actual_hash_value=$(sha256sum /usr/bin/sha256sum | awk '{print $1}')
    if [ "$trusted_hash_value" != "$actual_hash_value" ]; then
        printf "suspicous\n"
        exit 1
    else
        printf "ok\n"
    fi

    printf "Checking sha256sum hash value 2..."
    trusted_hash_value="ae35d20c02858dce2ce5083194f43cec"
    actual_hash_value=$(md5sum /usr/bin/sha256sum | awk '{print $1}')
    if [ "$trusted_hash_value" != "$actual_hash_value" ]; then
        printf "suspicous\n"
        exit 1
    else
        printf "ok\n"
    fi
}

check_hashes_file__authentication ()
{
    printf "Checking hash file authentication... "
    mod_date_of_hashes_file=$(date -r "$HASHES_FILE")
    if [ "$mod_date_of_hashes_file" != "Thu 01 Jan 1970 12:00:00 PM CET" ]; then
        printf "suspicous\n"
        exit 1
    else
        printf "ok\n"
    fi
}

update_index ()
{
    echo "Updating hashes..."
    for f in $files; do
        echo "Updating $f..."
        sha256sum $f >> "$HASHES_FILE"
    done
    echo ""
    echo "Hashes have been updated."

    touch -d "1970-01-01 12:00:00" "$HASHES_FILE"
}

check_index ()
{
    changed=0
    missing=0
    while IFS= read -r line; do
        fname=$(echo $line | awk '{print $2}')
        printf "Checking '$fname'... "

        if [ ! -f "$fname" ]; then
            echo "missing"
            missing=$((missing + 1))
            continue
        fi

        old_hash=$(echo $line | awk '{print $1}')
        current_hash=$(sha256sum $fname | awk '{print $1}')
        if [ "$old_hash" != "$current_hash" ]; then
            echo "changed"
            changed=$((changed + 1))
        else
            echo "nothing changed"
        fi
    done < "$HASHES_FILE"

    echo
    echo
    echo "Results"
    echo "-------"
    echo "Changed files : $changed"
    echo "Missing files : $missing"

    if [ $(echo "$files" | wc -l) -gt $(cat $HASHES_FILE | wc -l) ]; then
        echo "Note: There are more files present than currently recorded"
        echo "in the hash file!"
    fi
}

##############################################################################
#
# Start of program
#
##############################################################################

if [ ! -f /usr/bin/sha256sum ]; then
    echo "No '/usr/bin/sha256sum' available."
    echo "Script will terminate."
    exit 1
fi

HASHES_FILE="$HOME/.config/chkbins/.chkbins.txt"

check_sha256sum_authentication

files=$(find /usr/bin/ -type f | sort && find /usr/sbin/ -type f | sort)
if [ ! -f "$HASHES_FILE" ]; then
    mkdir -p $(dirname $HASHES_FILE) > /dev/zero
    update_index
else
    check_hashes_file__authentication
    check_index
fi

