#!/usr/bin/env bash

#
# Check bin files for any changes/tampering.
# - Niklas Schultz
#

##############################################################################
#
# Global function definitions
#
##############################################################################

check_sha256sum_authentication ()
{
    printf "Checking sha256sum authentication (size)... "
    size_in_bytes=$(du -b /usr/bin/sha256sum | awk '{print $1}')
    if [ "$size_in_bytes" != "59768" ]; then
        printf "suspicous\n"
        exit 1
    else
        printf "ok\n"
    fi

    printf "Checking sha256sum authentication (date)... "
    last_mod_time=$(date -r /usr/bin/sha256sum)
    if [ "$last_mod_time" != "Thu 05 Sep 2019 12:38:40 PM CEST" ]; then
        printf "suspicous\n"
        exit 1
    else
        printf "ok\n"
    fi

    printf "Checking sha256sum authentication (header)... "
    header=$(hexdump -v /usr/bin/sha256sum | head -1 | awk '{print $2$3$4$5$6$7$8$9}')
    if [ $header != "457f464c010200010000000000000000" ]; then
        printf "suspicous\n"
        exit 1
    else
        printf "ok\n"
    fi

    printf "Checking sha256sum authentication (hexdump)... "
    # we are just checking a random sequence of bytes
    if [ $(hexdump -v /usr/bin/sha256sum | grep 000e730 | awk '{print $6}') != "00d5" ]; then
        printf "suspicous\n"
        exit 1
    else
        printf "ok\n"
    fi

    printf "Checking sha256sum authentication (strings)... "
    if [ $(strings /usr/bin/sha256sum | wc -l) != 536 ]; then
        printf "suspicous\n"
        exit 1
    else
        printf "ok\n"
    fi

    printf "Checking sha256sum authentication (base64)... "
    padding_count=$(base64 /usr/bin/sha256sum | grep -o "=" | wc -l)
    random_char_count=$(base64 /usr/bin/sha256sum | grep -o "A" | wc -l)
    if [ $padding_count != 1 ] || [ $random_char_count != 25746 ]; then
        printf "suspicous\n"
        exit 1
    else
        printf "ok\n"
    fi

    printf "Checking sha256sum authentication (sha256)... "
    trusted_hash_value="b693d4bd026ba1515edacabcadbd6785454b08ec9468665e4dc33f01df8cc659"
    actual_hash_value=$(sha256sum /usr/bin/sha256sum | awk '{print $1}')
    if [ "$trusted_hash_value" != "$actual_hash_value" ]; then
        printf "suspicous\n"
        exit 1
    else
        printf "ok\n"
    fi

    printf "Checking sha256sum authentication (sha1)... "
    trusted_hash_value="6ba3d35c8c22f07339cb519adb78273630badeb2"
    actual_hash_value=$(sha1sum /usr/bin/sha256sum | awk '{print $1}')
    if [ "$trusted_hash_value" != "$actual_hash_value" ]; then
        printf "suspicous\n"
        exit 1
    else
        printf "ok\n"
    fi

    printf "Checking sha256sum authentication (md5)... "
    trusted_hash_value="ae35d20c02858dce2ce5083194f43cec"
    actual_hash_value=$(md5sum /usr/bin/sha256sum | awk '{print $1}')
    if [ "$trusted_hash_value" != "$actual_hash_value" ]; then
        printf "suspicous\n"
        exit 1
    else
        printf "ok\n"
    fi
}

check_hashes_file_authentication ()
{
    printf "Checking hash file authentication... "
    mod_date_of_hashes_file=$(date -r "$HASHES_FILE")
    if [ "$mod_date_of_hashes_file" != "Thu 01 Jan 1970 12:00:00 PM CET" ]; then
        printf "suspicous\n"
        exit 1
    else
        printf "ok\n"
    fi
}

update_index ()
{
    echo "Updating hashes..."
    for f in $files; do
        echo "Updating $f..."
        sha256sum $f >> "$HASHES_FILE"
    done
    echo ""
    echo "Hashes have been updated."

    touch -d "1970-01-01 12:00:00" "$HASHES_FILE"
}

check_index ()
{
    changed=0
    missing=0
    added=0
    while IFS= read -r line; do
        fname=$(echo $line | awk '{print $2}')
        printf "Checking '$fname'... "

        if [ ! -f "$fname" ]; then
            echo "missing"
            missing=$((missing + 1))
            continue
        fi

        old_hash=$(echo $line | awk '{print $1}')
        current_hash=$(sha256sum $fname | awk '{print $1}')
        if [ "$old_hash" != "$current_hash" ]; then
            echo "changed"
            changed=$((changed + 1))
        else
            echo "nothing changed"
        fi
    done < "$HASHES_FILE"
    
    echo "Checking for new files... "
    for f in $files; do
        grep -F -w -q "$f" "$HASHES_FILE"
        if [ $? -ne 0 ]; then
            echo "'$f'"
            added=$((added + 1))
        fi
    done

    echo
    echo
    echo "Results"
    echo "-------"
    echo "Changed files : $changed"
    echo "Missing files : $missing"
    echo "Added   files : $added"

    echo
    if [ $changed != 0 ] || [ $missing != 0 ] || [ $added != 0 ]; then
        echo "Changes detected: Possible security breach!"
    fi
}

##############################################################################
#
# Start of program
#
##############################################################################

if [ ! -f /usr/bin/sha256sum ]; then
    echo "No '/usr/bin/sha256sum' available."
    echo "Script will terminate."
    exit 1
fi

if [ ! -f /usr/bin/sha1sum ]; then
    echo "No '/usr/bin/sha1sum' available."
    echo "Script will terminate."
    exit 1
fi

if [ ! -f /usr/bin/md5sum ]; then
    echo "No '/usr/bin/sha1sum' available."
    echo "Script will terminate."
    exit 1
fi

HASHES_FILE="$HOME/.config/chkfiles/.chkfiles.txt"

check_sha256sum_authentication

printf "Gathering files... "
files=$(find /etc/passwd | sort && find /etc/hosts | sort && find /etc/xdg/autostart/ -type f | sort && find /usr/bin/ -type f | sort && find /usr/sbin/ -type f | sort)
printf "done\n"
if [ ! -f "$HASHES_FILE" ]; then
    mkdir -p $(dirname $HASHES_FILE) > /dev/zero
    update_index
else
    check_hashes_file_authentication
    check_index
fi

