#!/usr/bin/env bash

#
# Checks important files for any changes.
# - Niklas Schultz
#

##############################################################################
#
# Global function definitions
#
##############################################################################

update_index ()
{
    echo "Updating hashes..."
    for f in $files; do
        echo "Getting sha256 for $f..."
        sha256sum $f >> $HOME/.chkhashes.txt
    done
    echo "Hashes have been updated."
}

check_index ()
{
    changed=0
    missing=0
    while IFS= read -r line; do
        fname=$(echo $line | awk '{print $2}')
        printf "Checking sha256 for $fname... "

        if [ ! -f "$fname" ]; then
            echo "missing"
            missing=$((missing + 1))
            continue
        fi

        old_hash=$(echo $line | awk '{print $1}')
        current_hash=$(sha256sum $fname | awk '{print $1}')
        if [ "$old_hash" != "$current_hash" ]; then
            echo "changed"
            changed=$((changed + 1))
        else
            echo "nothing changed"
        fi
    done < $HOME/.chkhashes.txt

    echo
    echo
    echo "Results"
    echo "-------"
    echo "Changed files : $changed"
    echo "Missing files : $missing"
}

##############################################################################
#
# Start of program
#
##############################################################################

files=$(find /usr/bin/ -type f | sort)
if [ ! -f $HOME/.chkhashes.txt ]; then
    update_index
else
    check_index
fi

