#!/usr/bin/env bash

if ! command -v sensors > /dev/null
then
    echo "No 'lm_sensors' installed on this machine."
    echo "Script will terminate!"
    exit 1
fi

output=$(sensors | awk '/^Core/ {print $3}')
mod_output=$(echo $output | sed 's/C//g' | sed 's/°//g' | sed 's/+//g' | sed 's/\.0//g')
c1=$(echo $mod_output | awk '{print $1}')
c2=$(echo $mod_output | awk '{print $2}')

reset='\033[0;0m'
green='\033[0;32m'
yellow='\033[0;33m'
red='\033[0;31m'

if (($c1 > 50)); then
    echo -e "Core1: ${red}${c1}°C${reset}"
elif (($c1 > 40)); then
    echo -e "Core1: ${yellow}${c1}°C${reset}"
else
    echo -e "Core1: ${green}${c1}°C${reset}"
fi

if (($c2 > 50)); then
    echo -e "Core2: ${red}${c2}°C${reset}"
elif (($c2 > 40)); then
    echo -e "Core2: ${yellow}${c2}°C${reset}"
else
    echo -e "Core2: ${green}${c2}°C${reset}"
fi
