#!/usr/bin/env bash

if ! command -v sensors > /dev/null
then
    echo "No 'lm_sensors' installed on this machine."
    echo "Script will terminate!"
    exit 1
fi

OUTPUT=$(sensors | awk '/^Core/ {print $3}')
MOD_OUTPUT=$(echo $OUTPUT | sed 's/C//g' | sed 's/°//g' | sed 's/+//g' | sed 's/\.0//g')
C1=$(echo $MOD_OUTPUT | awk '{print $1}')
C2=$(echo $MOD_OUTPUT | awk '{print $2}')

RESET='\033[0;0m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'

if (($C1 > 50)); then
    echo -e "Core1: ${RED}${C1}°C${RESET}"
elif (($C1 > 40)); then
    echo -e "Core1: ${YELLOW}${C1}°C${RESET}"
else
    echo -e "Core1: ${GREEN}${C1}°C${RESET}"
fi

if (($C2 > 50)); then
    echo -e "Core2: ${RED}${C2}°C${RESET}"
elif (($C2 > 40)); then
    echo -e "Core2: ${YELLOW}${C2}°C${RESET}"
else
    echo -e "Core2: ${GREEN}${C2}°C${RESET}"
fi
