#!/usr/bin/env bash

if ! command -v rkhunter > /dev/null
then
    echo "No 'rkhunter' installed on this machine."
    echo "Script will terminate!"
    exit 1
fi

if ! command -v chkrootkit > /dev/null
then
    echo "No 'chkrootkit' installed on this machine."
    echo "Script will terminate!"
    exit 1
fi

sudo -s eval 'echo && echo [ Firewall ] && ufw status && echo && sleep 2 && echo [ chkrootkit ] && chkrootkit && echo && sleep 2 && rkhunter --sk --check'
