#!/usr/bin/env bash

if ! command -v ffmpeg > /dev/null
then
    echo "No 'ffmpeg' installed on this machine."
    echo "Script will terminate!"
    exit 1
fi

trap abort SIGINT
abort() {
    exit 0
}

if [ -d "$1" ]
then
    for f in *.mp4
    do
        mp3=$(echo $f | sed 's/mp4/mp3/')
        ffmpeg -i "$f" "$mp3"
    done
else
    mp3=$(echo $1 | sed 's/mp4/mp3/')
    ffmpeg -i "$1" "$mp3"
fi

