#!/usr/bin/env bash

#
# Displays the top 10 processes by cpu and ram usage.
# - Niklas Schultz
#

echo
echo "[ RAM ]"
echo
ps axch -o cmd:20,%mem --sort=-%mem | head
echo
echo "[ CPU ]"
echo
ps axch -o cmd:20,%cpu --sort=-%cpu | head
